'use server';
/**
 * @fileOverview An AI agent that generates text from a user prompt.
 *
 * - generateTextFromText - A function that takes a user prompt and returns generated text.
 * - GenerateTextFromTextInput - The input type for the generateTextFromText function.
 * - GenerateTextFromTextOutput - The return type for the generateTextFromText function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTextFromTextInputSchema = z.object({
  prompt: z.string().describe('The prompt to generate text from.'),
});
export type GenerateTextFromTextInput = z.infer<
  typeof GenerateTextFromTextInputSchema
>;

const GenerateTextFromTextOutputSchema = z.object({
  generatedText: z
    .string()
    .describe('The text generated by the AI.'),
});
export type GenerateTextFromTextOutput = z.infer<
  typeof GenerateTextFromTextOutputSchema
>;

export async function generateTextFromText(
  input: GenerateTextFromTextInput
): Promise<GenerateTextFromTextOutput> {
  return generateTextFromTextFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTextFromTextPrompt',
  input: {schema: GenerateTextFromTextInputSchema},
  output: {schema: GenerateTextFromTextOutputSchema},
  prompt: `You are a creative writer. Generate content based on the following prompt:\n\n{{{prompt}}}`,
});

const generateTextFromTextFlow = ai.defineFlow(
  {
    name: 'generateTextFromTextFlow',
    inputSchema: GenerateTextFromTextInputSchema,
    outputSchema: GenerateTextFromTextOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
